const { Report, SensorData, User } = require('../models');
const ReportGenerator = require('../utils/reportGenerator');
const EmailService = require('../utils/emailService');
const Helpers = require('../utils/helpers');
const { USER_ROLES, REPORT_TYPES } = require('../config/constants');
const fs = require('fs');
const path = require('path');

class ReportController {
    // Render reports page
    static async renderReports(req, res) {
        try {
            const { type, page = 1 } = req.query;
            
            // Build query
            const query = {};
            
            if (type && Object.values(REPORT_TYPES).includes(type)) {
                query.type = type;
            }
            
            // Only show public reports or reports generated by user
            if (req.session.user.role !== USER_ROLES.ADMIN) {
                query.$or = [
                    { isPublic: true },
                    { generatedBy: req.session.user.id },
                    { sharedWith: req.session.user.id }
                ];
            }
            
            // Pagination
            const pageSize = 10;
            const skip = (parseInt(page) - 1) * pageSize;
            
            // Get total count
            const total = await Report.countDocuments(query);
            
            // Get reports
            const reports = await Report.find(query)
                .sort({ 'period.endDate': -1 })
                .skip(skip)
                .limit(pageSize)
                .populate('generatedBy', 'name email');
            
            // Calculate pagination
            const totalPages = Math.ceil(total / pageSize);
            const pagination = Helpers.createPagination(total, parseInt(page), pageSize);
            
            // Get report statistics
            const stats = await Report.getStatistics();
            
            res.render('pages/reports', {
                title: 'Reports - Solar Monitoring System',
                user: req.session.user,
                reports,
                pagination,
                stats,
                filters: { type },
                reportTypes: REPORT_TYPES,
                helpers: Helpers,
                success: req.query.success || null,
                error: req.query.error || null
            });
            
        } catch (error) {
            console.error('Render reports error:', error);
            res.status(500).render('pages/reports', {
                title: 'Reports - Solar Monitoring System',
                user: req.session.user,
                reports: [],
                pagination: null,
                stats: null,
                filters: {},
                reportTypes: REPORT_TYPES,
                helpers: Helpers,
                success: null,
                error: 'Failed to load reports'
            });
        }
    }
    
    // Generate report (API)
    static async generateReport(req, res) {
        try {
            const {
                type = REPORT_TYPES.DAILY,
                format = 'pdf',
                startDate,
                endDate,
                includeRawData = false,
                emailRecipients = []
            } = req.body;
            
            const userId = req.session.user.id;
            
            // Validate dates
            let reportStartDate, reportEndDate;
            
            if (startDate && endDate) {
                reportStartDate = new Date(startDate);
                reportEndDate = new Date(endDate);
                
                if (reportStartDate > reportEndDate) {
                    return res.status(400).json({
                        success: false,
                        message: 'Start date must be before end date'
                    });
                }
            } else {
                // Use default dates based on type
                const now = new Date();
                
                switch (type) {
                    case REPORT_TYPES.DAILY:
                        reportStartDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);
                        reportEndDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 23, 59, 59);
                        break;
                    case REPORT_TYPES.WEEKLY:
                        reportStartDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7);
                        reportEndDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 23, 59, 59);
                        break;
                    case REPORT_TYPES.MONTHLY:
                        reportStartDate = new Date(now.getFullYear(), now.getMonth() - 1, 1);
                        reportEndDate = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59);
                        break;
                    default:
                        reportStartDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);
                        reportEndDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 23, 59, 59);
                }
            }
            
            // Get sensor data for the period
            const sensorData = await SensorData.getRange(reportStartDate, reportEndDate);
            
            if (sensorData.length === 0) {
                return res.status(404).json({
                    success: false,
                    message: 'No data available for the specified period'
                });
            }
            
            // Generate report
            const reportResult = await ReportGenerator.generateReport(
                sensorData,
                reportStartDate,
                reportEndDate,
                {
                    type,
                    format,
                    includeRawData
                }
            );
            
            // Create report document
            const report = new Report({
                title: Report.generateTitle(type, reportStartDate, reportEndDate),
                type,
                period: {
                    startDate: reportStartDate,
                    endDate: reportEndDate
                },
                generatedBy: userId,
                filePath: reportResult.filePath,
                fileName: reportResult.fileName,
                fileSize: reportResult.fileSize,
                format: reportResult.format,
                summary: reportResult.summary,
                metadata: {
                    generationTime: 0, // Would calculate actual generation time
                    dataPointsUsed: sensorData.length,
                    chartsIncluded: true,
                    recommendationsCount: 0,
                    anomaliesDetected: 0
                },
                isPublic: req.session.user.role === USER_ROLES.ADMIN
            });
            
            await report.save();
            
            // Send email if recipients specified
            if (emailRecipients && emailRecipients.length > 0 && reportResult.filePath) {
                try {
                    for (const email of emailRecipients) {
                        await EmailService.sendReportEmail(
                            email,
                            reportResult.filePath,
                            type
                        );
                    }
                    
                    report.emailSent = true;
                    report.emailSentTo = emailRecipients;
                    report.emailSentAt = new Date();
                    await report.save();
                } catch (emailError) {
                    console.error('Failed to send report email:', emailError);
                    // Don't fail report generation if email fails
                }
            }
            
            // Increment download count
            await Report.incrementDownload(report._id);
            
            res.json({
                success: true,
                message: 'Report generated successfully',
                data: {
                    reportId: report._id,
                    title: report.title,
                    filePath: report.filePath,
                    fileName: report.fileName,
                    downloadUrl: `/api/reports/download/${report._id}`,
                    previewUrl: `/api/reports/preview/${report._id}`,
                    generatedAt: report.createdAt
                }
            });
            
        } catch (error) {
            console.error('Generate report error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to generate report',
                error: error.message
            });
        }
    }
    
    // Download report (API)
    static async downloadReport(req, res) {
        try {
            const { id } = req.params;
            
            const report = await Report.findById(id);
            
            if (!report) {
                return res.status(404).json({
                    success: false,
                    message: 'Report not found'
                });
            }
            
            // Check permissions
            if (!report.isPublic && 
                report.generatedBy.toString() !== req.session.user.id &&
                !report.sharedWith.includes(req.session.user.id) &&
                req.session.user.role !== USER_ROLES.ADMIN) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied to this report'
                });
            }
            
            // Check if file exists
            const filePath = path.join(__dirname, '../../', report.filePath);
            
            if (!fs.existsSync(filePath)) {
                return res.status(404).json({
                    success: false,
                    message: 'Report file not found'
                });
            }
            
            // Increment download count
            await Report.incrementDownload(id);
            
            // Set headers for download
            res.setHeader('Content-Type', report.getMimeType());
            res.setHeader('Content-Disposition', `attachment; filename="${report.fileName}"`);
            
            // Stream file
            const fileStream = fs.createReadStream(filePath);
            fileStream.pipe(res);
            
        } catch (error) {
            console.error('Download report error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to download report',
                error: error.message
            });
        }
    }
    
    // Preview report (API)
    static async previewReport(req, res) {
        try {
            const { id } = req.params;
            
            const report = await Report.findById(id);
            
            if (!report) {
                return res.status(404).json({
                    success: false,
                    message: 'Report not found'
                });
            }
            
            // Check permissions
            if (!report.isPublic && 
                report.generatedBy.toString() !== req.session.user.id &&
                !report.sharedWith.includes(req.session.user.id) &&
                req.session.user.role !== USER_ROLES.ADMIN) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied to this report'
                });
            }
            
            // Only PDF can be previewed
            if (report.format !== 'pdf') {
                return res.status(400).json({
                    success: false,
                    message: 'Only PDF reports can be previewed'
                });
            }
            
            // Check if file exists
            const filePath = path.join(__dirname, '../../', report.filePath);
            
            if (!fs.existsSync(filePath)) {
                return res.status(404).json({
                    success: false,
                    message: 'Report file not found'
                });
            }
            
            // Set headers for inline viewing
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', `inline; filename="${report.fileName}"`);
            
            // Stream file
            const fileStream = fs.createReadStream(filePath);
            fileStream.pipe(res);
            
        } catch (error) {
            console.error('Preview report error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to preview report',
                error: error.message
            });
        }
    }
    
    // Get report by ID (API)
    static async getReportById(req, res) {
        try {
            const { id } = req.params;
            
            const report = await Report.findById(id)
                .populate('generatedBy', 'name email')
                .populate('sharedWith', 'name email');
            
            if (!report) {
                return res.status(404).json({
                    success: false,
                    message: 'Report not found'
                });
            }
            
            // Check permissions
            if (!report.isPublic && 
                report.generatedBy.toString() !== req.session.user.id &&
                !report.sharedWith.includes(req.session.user.id) &&
                req.session.user.role !== USER_ROLES.ADMIN) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied to this report'
                });
            }
            
            res.json({
                success: true,
                data: report
            });
            
        } catch (error) {
            console.error('Get report by ID error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get report',
                error: error.message
            });
        }
    }
    
    // Get reports with filters (API)
    static async getReports(req, res) {
        try {
            const {
                type,
                startDate,
                endDate,
                format,
                limit = 20,
                page = 1,
                sort = '-period.endDate'
            } = req.query;
            
            // Build query
            const query = {};
            
            if (type && Object.values(REPORT_TYPES).includes(type)) {
                query.type = type;
            }
            
            if (format) {
                query.format = format;
            }
            
            // Date range
            if (startDate || endDate) {
                query['period.startDate'] = {};
                if (startDate) query['period.startDate'].$gte = new Date(startDate);
                if (endDate) query['period.startDate'].$lte = new Date(endDate);
            }
            
            // Only show public reports or reports generated by user
            if (req.session.user.role !== USER_ROLES.ADMIN) {
                query.$or = [
                    { isPublic: true },
                    { generatedBy: req.session.user.id },
                    { sharedWith: req.session.user.id }
                ];
            }
            
            // Pagination
            const pageSize = parseInt(limit);
            const skip = (parseInt(page) - 1) * pageSize;
            
            // Get total count
            const total = await Report.countDocuments(query);
            
            // Get reports
            const reports = await Report.find(query)
                .sort(sort)
                .skip(skip)
                .limit(pageSize)
                .populate('generatedBy', 'name email');
            
            // Calculate pagination metadata
            const totalPages = Math.ceil(total / pageSize);
            const pagination = Helpers.createPagination(total, parseInt(page), pageSize);
            
            res.json({
                success: true,
                pagination,
                count: reports.length,
                total,
                data: reports
            });
            
        } catch (error) {
            console.error('Get reports error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get reports',
                error: error.message
            });
        }
    }
    
    // Update report (admin only - API)
    static async updateReport(req, res) {
        try {
            const { id } = req.params;
            const { title, isPublic, tags, sharedWith } = req.body;
            
            // Check if user is admin or report owner
            const report = await Report.findById(id);
            
            if (!report) {
                return res.status(404).json({
                    success: false,
                    message: 'Report not found'
                });
            }
            
            if (req.session.user.role !== USER_ROLES.ADMIN && 
                report.generatedBy.toString() !== req.session.user.id) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied. Only admin or report owner can update.'
                });
            }
            
            // Update fields
            if (title) report.title = title;
            if (typeof isPublic === 'boolean') report.isPublic = isPublic;
            if (tags && Array.isArray(tags)) report.tags = tags;
            
            if (sharedWith && Array.isArray(sharedWith)) {
                // Validate user IDs
                const validUsers = await User.find({ _id: { $in: sharedWith } });
                report.sharedWith = validUsers.map(user => user._id);
            }
            
            await report.save();
            
            res.json({
                success: true,
                message: 'Report updated successfully',
                data: report
            });
            
        } catch (error) {
            console.error('Update report error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to update report',
                error: error.message
            });
        }
    }
    
    // Delete report (admin only - API)
    static async deleteReport(req, res) {
        try {
            const { id } = req.params;
            
            // Check if user is admin
            if (req.session.user.role !== USER_ROLES.ADMIN) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied. Admin privileges required.'
                });
            }
            
            const report = await Report.findById(id);
            
            if (!report) {
                return res.status(404).json({
                    success: false,
                    message: 'Report not found'
                });
            }
            
            // Delete file from filesystem
            const filePath = path.join(__dirname, '../../', report.filePath);
            if (fs.existsSync(filePath)) {
                fs.unlinkSync(filePath);
            }
            
            await report.deleteOne();
            
            res.json({
                success: true,
                message: 'Report deleted successfully'
            });
            
        } catch (error) {
            console.error('Delete report error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to delete report',
                error: error.message
            });
        }
    }
    
    // Send report via email (API)
    static async sendReportEmail(req, res) {
        try {
            const { id } = req.params;
            const { emails } = req.body;
            
            if (!emails || !Array.isArray(emails) || emails.length === 0) {
                return res.status(400).json({
                    success: false,
                    message: 'Please provide email addresses'
                });
            }
            
            const report = await Report.findById(id);
            
            if (!report) {
                return res.status(404).json({
                    success: false,
                    message: 'Report not found'
                });
            }
            
            // Check permissions
            if (req.session.user.role !== USER_ROLES.ADMIN && 
                report.generatedBy.toString() !== req.session.user.id) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied. Only admin or report owner can send emails.'
                });
            }
            
            // Check if file exists
            const filePath = path.join(__dirname, '../../', report.filePath);
            
            if (!fs.existsSync(filePath)) {
                return res.status(404).json({
                    success: false,
                    message: 'Report file not found'
                });
            }
            
            // Send emails
            const sentEmails = [];
            const failedEmails = [];
            
            for (const email of emails) {
                try {
                    await EmailService.sendReportEmail(email, filePath, report.type);
                    sentEmails.push(email);
                } catch (emailError) {
                    console.error(`Failed to send email to ${email}:`, emailError);
                    failedEmails.push({ email, error: emailError.message });
                }
            }
            
            // Update report
            report.emailSent = true;
            report.emailSentTo = [...new Set([...(report.emailSentTo || []), ...sentEmails])];
            report.emailSentAt = new Date();
            await report.save();
            
            res.json({
                success: true,
                message: `Report sent to ${sentEmails.length} email(s)`,
                sentEmails,
                failedEmails
            });
            
        } catch (error) {
            console.error('Send report email error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to send report email',
                error: error.message
            });
        }
    }
    
    // Generate and send scheduled report (API - for cron jobs)
    static async generateScheduledReport(req, res) {
        try {
            const { type, emails } = req.body;
            
            if (!type || !Object.values(REPORT_TYPES).includes(type)) {
                return res.status(400).json({
                    success: false,
                    message: 'Invalid report type'
                });
            }
            
            // Generate report
            const sensorData = await SensorData.find({
                timestamp: { 
                    $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) // Last 24 hours
                }
            });
            
            if (sensorData.length === 0) {
                return res.status(404).json({
                    success: false,
                    message: 'No data available for report generation'
                });
            }
            
            const now = new Date();
            const startDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);
            const endDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 23, 59, 59);
            
            const reportResult = await ReportGenerator.generateReport(
                sensorData,
                startDate,
                endDate,
                { type, format: 'pdf' }
            );
            
            // Create report document
            const report = new Report({
                title: Report.generateTitle(type, startDate, endDate),
                type,
                period: { startDate, endDate },
                generatedBy: req.session.user.id,
                filePath: reportResult.filePath,
                fileName: reportResult.fileName,
                fileSize: reportResult.fileSize,
                format: reportResult.format,
                summary: reportResult.summary,
                isPublic: true
            });
            
            await report.save();
            
            // Send emails if specified
            if (emails && Array.isArray(emails) && emails.length > 0) {
                try {
                    for (const email of emails) {
                        await EmailService.sendReportEmail(email, reportResult.filePath, type);
                    }
                    
                    report.emailSent = true;
                    report.emailSentTo = emails;
                    report.emailSentAt = new Date();
                    await report.save();
                } catch (emailError) {
                    console.error('Failed to send scheduled report email:', emailError);
                }
            }
            
            res.json({
                success: true,
                message: 'Scheduled report generated successfully',
                data: {
                    reportId: report._id,
                    title: report.title,
                    generatedAt: report.createdAt
                }
            });
            
        } catch (error) {
            console.error('Generate scheduled report error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to generate scheduled report',
                error: error.message
            });
        }
    }
    
    // Get most downloaded reports (API)
    static async getPopularReports(req, res) {
        try {
            const { limit = 10 } = req.query;
            
            const reports = await Report.getMostDownloaded(parseInt(limit));
            
            res.json({
                success: true,
                count: reports.length,
                data: reports
            });
            
        } catch (error) {
            console.error('Get popular reports error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get popular reports',
                error: error.message
            });
        }
    }
    
    // Clean up old reports (admin only - API)
    static async cleanupOldReports(req, res) {
        try {
            // Check if user is admin
            if (req.session.user.role !== USER_ROLES.ADMIN) {
                return res.status(403).json({
                    success: false,
                    message: 'Access denied. Admin privileges required.'
                });
            }
            
            const { days = 90 } = req.query;
            
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - parseInt(days));
            
            // Find reports older than cutoff
            const oldReports = await Report.find({
                'period.endDate': { $lt: cutoffDate }
            });
            
            let deletedCount = 0;
            let fileDeleteErrors = [];
            
            // Delete files and records
            for (const report of oldReports) {
                try {
                    // Delete file
                    const filePath = path.join(__dirname, '../../', report.filePath);
                    if (fs.existsSync(filePath)) {
                        fs.unlinkSync(filePath);
                    }
                    
                    // Delete record
                    await report.deleteOne();
                    deletedCount++;
                } catch (error) {
                    fileDeleteErrors.push({
                        reportId: report._id,
                        fileName: report.fileName,
                        error: error.message
                    });
                }
            }
            
            res.json({
                success: true,
                message: `Cleaned up ${deletedCount} reports older than ${days} days`,
                deletedCount,
                errors: fileDeleteErrors
            });
            
        } catch (error) {
            console.error('Cleanup old reports error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to cleanup old reports',
                error: error.message
            });
        }
    }

        // Add these methods to the ReportController class

// Get report templates (API)
static async getReportTemplates(req, res) {
    try {
        const templates = [
            {
                id: 'daily_performance',
                name: 'Daily Performance Report',
                type: 'daily',
                description: 'Daily system performance and energy production',
                defaultFormat: 'pdf',
                charts: ['energy_production', 'voltage_trend', 'temperature_trend']
            },
            {
                id: 'weekly_summary',
                name: 'Weekly Summary Report',
                type: 'weekly',
                description: 'Weekly summary with trends and comparisons',
                defaultFormat: 'pdf',
                charts: ['weekly_comparison', 'efficiency_analysis', 'alert_summary']
            },
            {
                id: 'monthly_analysis',
                name: 'Monthly Analysis Report',
                type: 'monthly',
                description: 'Comprehensive monthly analysis with recommendations',
                defaultFormat: 'pdf',
                charts: ['monthly_trends', 'performance_metrics', 'maintenance_schedule']
            },
            {
                id: 'custom_analysis',
                name: 'Custom Analysis Report',
                type: 'custom',
                description: 'Custom report with selected parameters',
                defaultFormat: 'pdf',
                charts: ['custom_charts']
            },
            {
                id: 'alert_summary',
                name: 'Alert Summary Report',
                type: 'custom',
                description: 'Summary of alerts and incidents',
                defaultFormat: 'pdf',
                charts: ['alert_trends', 'severity_distribution', 'resolution_time']
            },
            {
                id: 'system_health',
                name: 'System Health Report',
                type: 'custom',
                description: 'Complete system health assessment',
                defaultFormat: 'pdf',
                charts: ['health_metrics', 'component_status', 'predictive_analysis']
            }
        ];
        
        res.json({
            success: true,
            templates
        });
        
    } catch (error) {
        console.error('Get report templates error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to get report templates',
            error: error.message
        });
    }
}

// Get report categories (API)
static async getReportCategories(req, res) {
    try {
        const categories = [
            {
                id: 'performance',
                name: 'Performance Reports',
                description: 'System performance and energy production',
                icon: 'chart-line',
                count: await Report.countDocuments({ type: { $in: ['daily', 'weekly', 'monthly'] } })
            },
            {
                id: 'analysis',
                name: 'Analysis Reports',
                description: 'Data analysis and insights',
                icon: 'chart-bar',
                count: await Report.countDocuments({ tags: 'analysis' })
            },
            {
                id: 'alerts',
                name: 'Alert Reports',
                description: 'Alert and incident summaries',
                icon: 'exclamation-triangle',
                count: await Report.countDocuments({ tags: 'alerts' })
            },
            {
                id: 'maintenance',
                name: 'Maintenance Reports',
                description: 'System maintenance and health',
                icon: 'tools',
                count: await Report.countDocuments({ tags: 'maintenance' })
            },
            {
                id: 'compliance',
                name: 'Compliance Reports',
                description: 'Regulatory and compliance reports',
                icon: 'file-contract',
                count: await Report.countDocuments({ tags: 'compliance' })
            },
            {
                id: 'custom',
                name: 'Custom Reports',
                description: 'User-generated custom reports',
                icon: 'edit',
                count: await Report.countDocuments({ type: 'custom' })
            }
        ];
        
        res.json({
            success: true,
            categories
        });
        
    } catch (error) {
        console.error('Get report categories error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to get report categories',
            error: error.message
        });
    }
}

// Get report trends (API)
static async getReportTrends(req, res) {
    try {
        const { days = 30 } = req.query;
        
        const endDate = new Date();
        const startDate = new Date();
        startDate.setDate(startDate.getDate() - parseInt(days));
        
        // Get reports grouped by day
        const reportsByDay = await Report.aggregate([
            {
                $match: {
                    createdAt: { $gte: startDate, $lte: endDate }
                }
            },
            {
                $group: {
                    _id: {
                        $dateToString: { format: '%Y-%m-%d', date: '$createdAt' }
                    },
                    total: { $sum: 1 },
                    pdf: {
                        $sum: { $cond: [{ $eq: ['$format', 'pdf'] }, 1, 0] }
                    },
                    excel: {
                        $sum: { $cond: [{ $eq: ['$format', 'excel'] }, 1, 0] }
                    },
                    csv: {
                        $sum: { $cond: [{ $eq: ['$format', 'csv'] }, 1, 0] }
                    },
                    totalSize: { $sum: '$fileSize' },
                    totalDownloads: { $sum: '$downloadCount' }
                }
            },
            { $sort: { _id: 1 } }
        ]);
        
        // Calculate statistics
        const totalReports = await Report.countDocuments({
            createdAt: { $gte: startDate, $lte: endDate }
        });
        
        const totalSize = await Report.aggregate([
            {
                $match: {
                    createdAt: { $gte: startDate, $lte: endDate }
                }
            },
            {
                $group: {
                    _id: null,
                    totalSize: { $sum: '$fileSize' }
                }
            }
        ]);
        
        const avgSize = totalReports > 0 ? 
            (totalSize[0]?.totalSize || 0) / totalReports : 0;
        
        const mostDownloaded = await Report.find({
            createdAt: { $gte: startDate, $lte: endDate }
        })
        .sort({ downloadCount: -1 })
        .limit(5)
        .select('title type format downloadCount createdAt');
        
        res.json({
            success: true,
            period: {
                start: startDate,
                end: endDate,
                days: parseInt(days)
            },
            trends: {
                daily: reportsByDay,
                totalReports,
                totalSize: totalSize[0]?.totalSize || 0,
                avgSize: Math.round(avgSize),
                mostDownloaded,
                byFormat: {
                    pdf: reportsByDay.reduce((sum, day) => sum + day.pdf, 0),
                    excel: reportsByDay.reduce((sum, day) => sum + day.excel, 0),
                    csv: reportsByDay.reduce((sum, day) => sum + day.csv, 0)
                }
            }
        });
        
    } catch (error) {
        console.error('Get report trends error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to get report trends',
            error: error.message
        });
    }
}

// Clone report (API)
static async cloneReport(req, res) {
    try {
        const { id } = req.params;
        const userId = req.session.user.id;
        
        const originalReport = await Report.findById(id);
        
        if (!originalReport) {
            return res.status(404).json({
                success: false,
                message: 'Report not found'
            });
        }
        
        // Check permissions
        if (!originalReport.isPublic && 
            originalReport.generatedBy.toString() !== userId &&
            !originalReport.sharedWith.includes(userId) &&
            req.session.user.role !== USER_ROLES.ADMIN) {
            return res.status(403).json({
                success: false,
                message: 'Access denied to this report'
            });
        }
        
        // Create cloned report
        const clonedReport = new Report({
            title: `Copy of ${originalReport.title}`,
            type: originalReport.type,
            period: originalReport.period,
            generatedBy: userId,
            filePath: originalReport.filePath,
            fileName: `copy_${originalReport.fileName}`,
            fileSize: originalReport.fileSize,
            format: originalReport.format,
            summary: originalReport.summary,
            metadata: originalReport.metadata,
            tags: [...(originalReport.tags || []), 'cloned'],
            isPublic: false, // Cloned reports are private by default
            sharedWith: []
        });
        
        await clonedReport.save();
        
        res.json({
            success: true,
            message: 'Report cloned successfully',
            data: {
                reportId: clonedReport._id,
                title: clonedReport.title,
                downloadUrl: `/api/reports/download/${clonedReport._id}`
            }
        });
        
    } catch (error) {
        console.error('Clone report error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to clone report',
            error: error.message
        });
    }
}

// Schedule report generation (API)
static async scheduleReport(req, res) {
    try {
        const {
            templateId,
            scheduleType,
            scheduleTime,
            recipients,
            format = 'pdf',
            includeCharts = true
        } = req.body;
        
        const userId = req.session.user.id;
        
        // Validate schedule type
        const validScheduleTypes = ['daily', 'weekly', 'monthly', 'custom'];
        if (!validScheduleTypes.includes(scheduleType)) {
            return res.status(400).json({
                success: false,
                message: 'Invalid schedule type'
            });
        }
        
        // Create schedule record (in a real implementation, you'd have a Schedule model)
        const schedule = {
            templateId,
            scheduleType,
            scheduleTime,
            recipients: recipients || [],
            format,
            includeCharts,
            createdBy: userId,
            isActive: true,
            nextRun: calculateNextRun(scheduleType, scheduleTime),
            lastRun: null
        };
        
        // In a real implementation, you'd save this to a database
        // For now, return success
        res.json({
            success: true,
            message: `Report scheduled for ${scheduleType} delivery`,
            schedule: {
                id: `schedule_${Date.now()}`,
                ...schedule
            }
        });
        
    } catch (error) {
        console.error('Schedule report error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to schedule report',
            error: error.message
        });
    }
}



// Get scheduled reports (API)
static async getScheduledReports(req, res) {
    try {
        // In a real implementation, you'd fetch from a Schedule model
        // For now, return mock data
        const scheduledReports = [
            {
                id: 'schedule_1',
                name: 'Daily Performance Report',
                scheduleType: 'daily',
                nextRun: new Date(Date.now() + 24 * 60 * 60 * 1000),
                lastRun: new Date(Date.now() - 24 * 60 * 60 * 1000),
                recipients: ['admin@example.com', 'tech@example.com'],
                format: 'pdf',
                isActive: true
            },
            {
                id: 'schedule_2',
                name: 'Weekly Summary Report',
                scheduleType: 'weekly',
                nextRun: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
                lastRun: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
                recipients: ['manager@example.com'],
                format: 'excel',
                isActive: true
            },
            {
                id: 'schedule_3',
                name: 'Monthly Analysis',
                scheduleType: 'monthly',
                nextRun: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
                lastRun: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
                recipients: ['director@example.com', 'finance@example.com'],
                format: 'pdf',
                isActive: true
            }
        ];
        
        res.json({
            success: true,
            scheduledReports
        });
        
    } catch (error) {
        console.error('Get scheduled reports error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to get scheduled reports',
            error: error.message
        });
    }
}
}

// Helper function to calculate next run time
function calculateNextRun(scheduleType, scheduleTime) {
    const now = new Date();
    const nextRun = new Date();
    
    switch (scheduleType) {
        case 'daily':
            nextRun.setDate(now.getDate() + 1);
            break;
        case 'weekly':
            nextRun.setDate(now.getDate() + 7);
            break;
        case 'monthly':
            nextRun.setMonth(now.getMonth() + 1);
            break;
        case 'custom':
            // Parse custom schedule time
            if (scheduleTime) {
                return new Date(scheduleTime);
            }
            break;
    }
    
    // Set time to 8:00 AM by default
    nextRun.setHours(8, 0, 0, 0);
    return nextRun;
}

module.exports = ReportController;